---

- hosts: all
  become: true
  tasks:

  - name: update repository index
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install pass package
    apt:
      name: pass
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: add php suppurt for apache
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"
