---
- hosts: all
  become: true
  tasks:

  - name: install pass and tmux packages
    package:
      name:
        - "{{ pass_package }}"
        - "{{ tmux_package }}"
      state: latest
      update_cache: yes
