---

- hosts: all
  become: true
  tasks:

#  - name: update repository index
#    apt:
#      update_cache: yes

  - name: remove pass package
    apt:
      name: pass
      state: absent
    when: ansible_distribution in ["Ubuntu"]

  - name: remove tmux package
    apt:
      name: tmux
      state: absent
    when: ansible_distribution in ["Ubuntu"]
