---

- hosts: all
  become: true
  tasks:

#  - name: update repository index
#    apt:
#      update_cache: yes

  - name: install pass package
    apt:
      name: pass
      state: absent

  - name: add php suppurt for apache
    apt:
      name: libapache2-mod-php
      state: absent
